# Generated by Django 4.2.5 on 2023-10-23 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['publication_date', 'author', 'tags']},
        ),
    ]
